import { z } from 'zod';

export const cocktailSchema = z.object({
    drinks: z.array(
      z.object({
        idDrink: z.string().optional(),        
        strDrink: z.string().nullable(),
        strDrinkAlternate: z.string().nullable().optional(),
        strTags: z.string().nullable(),
        strVideo: z.string().nullable().optional(),
        strCategory: z.string().nullable(),
        strIBA: z.string().nullable().optional(),
        strAlcoholic: z.string().nullable(),
        strGlass: z.string().nullable(),
        strInstructions: z.string().nullable(),
        strInstructionsES: z.string().nullable().optional(),
        strInstructionsDE: z.string().nullable().optional(),
        strInstructionsFR: z.string().nullable().optional(),
        strInstructionsIT: z.string().nullable().optional(),
        "strInstructionsZH-HANS": z.string().nullable().optional(),
        "strInstructionsZH-HANT": z.string().nullable().optional(),
        strDrinkThumb: z.string().nullable().optional(),
        strIngredient1: z.string().nullable(),
        strIngredient2: z.string().nullable().optional(),
        strIngredient3: z.string().nullable().optional(),
        strIngredient4: z.string().nullable().optional(),
        strIngredient5: z.string().nullable().optional(),
        strIngredient6: z.string().nullable().optional(),
        strIngredient7: z.string().nullable().optional(),
        strIngredient8: z.string().nullable().optional(),
        strIngredient9: z.string().nullable().optional(),
        strIngredient10: z.string().nullable().optional(),
        strIngredient11: z.string().nullable().optional(),
        strIngredient12: z.string().nullable().optional(),
        strIngredient13: z.string().nullable().optional(),
        strIngredient14: z.string().nullable().optional(),
        strIngredient15: z.string().nullable().optional(),
        strMeasure1: z.string().nullable(),
        strMeasure2: z.string().nullable().optional(),
        strMeasure3: z.string().nullable().optional(),
        strMeasure4: z.string().nullable().optional(),
        strMeasure5: z.string().nullable().optional(),
        strMeasure6: z.string().nullable().optional(),
        strMeasure7: z.string().nullable().optional(),
        strMeasure8: z.string().nullable().optional(),
        strMeasure9: z.string().nullable().optional(),
        strMeasure10: z.string().nullable().optional(),
        strMeasure11: z.string().nullable().optional(),
        strMeasure12: z.string().nullable().optional(),
        strMeasure13: z.string().nullable().optional(),
        strMeasure14: z.string().nullable().optional(),
        strMeasure15: z.string().nullable().optional(),
        strImageSource: z.string().nullable().optional(),
        strImageAttribution: z.string().nullable().optional(),
        strCreativeCommonsConfirmed: z.string().nullable(),
        dateModified: z.string().nullable(),
      }).strict()
    ),
  });